export const COUNTRIES: { label: string; value: string }[] = [
  { label: '🇦🇷 Argentina', value: '🇦🇷' },
  { label: '🇦🇲 Armenia', value: '🇦🇲' },
  { label: '🇦🇺 Australia', value: '🇦🇺' },
  { label: '🇦🇹 Austria', value: '🇦🇹' },
  { label: '🇦🇿 Azerbaijan', value: '🇦🇿' },
  { label: '🇧🇾 Belarus', value: '🇧🇾' },
  { label: '🇧🇷 Brazil', value: '🇧🇷' },
  { label: '🇧🇬 Bulgaria', value: '🇧🇬' },
  { label: '🇨🇦 Canada', value: '🇨🇦' },
  { label: '🇨🇳 China', value: '🇨🇳' },
  { label: '🇭🇷 Croatia', value: '🇭🇷' },
  { label: '🇨🇺 Cuba', value: '🇨🇺' },
  { label: '🇨🇿 Czech Republic', value: '🇨🇿' },
  { label: '🇩🇰 Denmark', value: '🇩🇰' },
  { label: '🇪🇬 Egypt', value: '🇪🇬' },
  { label: '🇫🇮 Finland', value: '🇫🇮' },
  { label: '🇫🇷 France', value: '🇫🇷' },
  { label: '🇬🇪 Georgia', value: '🇬🇪' },
  { label: '🇩🇪 Germany', value: '🇩🇪' },
  { label: '🇬🇷 Greece', value: '🇬🇷' },
  { label: '🇭🇺 Hungary', value: '🇭🇺' },
  { label: '🇮🇳 India', value: '🇮🇳' },
  { label: '🇮🇷 Iran', value: '🇮🇷' },
  { label: '🇮🇱 Israel', value: '🇮🇱' },
  { label: '🇮🇹 Italy', value: '🇮🇹' },
  { label: '🇯🇵 Japan', value: '🇯🇵' },
  { label: '🇰🇿 Kazakhstan', value: '🇰🇿' },
  { label: '🇲🇽 Mexico', value: '🇲🇽' },
  { label: '🇳🇱 Netherlands', value: '🇳🇱' },
  { label: '🇳🇴 Norway', value: '🇳🇴' },
  { label: '🇵🇱 Poland', value: '🇵🇱' },
  { label: '🇵🇹 Portugal', value: '🇵🇹' },
  { label: '🇷🇴 Romania', value: '🇷🇴' },
  { label: '🇷🇺 Russia', value: '🇷🇺' },
  { label: '🇸🇰 Slovakia', value: '🇸🇰' },
  { label: '🇪🇸 Spain', value: '🇪🇸' },
  { label: '🇸🇪 Sweden', value: '🇸🇪' },
  { label: '🇨🇭 Switzerland', value: '🇨🇭' },
  { label: '🇺🇦 Ukraine', value: '🇺🇦' },
  { label: '🇬🇧 United Kingdom', value: '🇬🇧' },
  { label: '🇺🇸 United States', value: '🇺🇸' },
  { label: '🇺🇿 Uzbekistan', value: '🇺🇿' },
  { label: '🇻🇳 Vietnam', value: '🇻🇳' },
]
