// Generated by Supabase CLI. Do not edit manually.
// Regenerate: supabase gen types typescript --project-id [project-id] > app/types/database.ts
// Or run: /types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
